export const SELECT_SEAT = 'SELECT_SEAT';
export const GET_SELECTED_SEATS_SUCCESS = 'GET_SELECTED_SEATS_SUCCESS';
export const GET_SELECTED_SEATS_FAILURE = 'GET_SELECTED_SEATS_FAILURE';
export const DELETE_SELECTED_SEATS = 'DELETE_SELECTED_SEATS';

