export const SELECT_SEAT = 'SELECT_SEAT';
export const DELETE_SELECTED_SEATS = 'DELETE_SELECTED_SEATS';
export const BUY_SEATS_SUCCESS = 'BUY_SEATS_SUCCESS';
export const BUY_SEATS_FAILURE = 'BUY_SEATS_FAILURE';
