export const SELECT_TICKET_SUCCESS = 'SELECT_TICKET_SUCCESS';
export const SELECT_TICKET_FAILURE = 'SELECT_TICKET_FAILURE';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';
